spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/student?useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    type: com.alibaba.druid.pool.DruidDataSource
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:db2://192.168.100.11:50000/students
    type: com.alibaba.druid.pool.DruidDataSource
    username: dwinst
    password: dwinst
    driver-class-name: com.ibm.db2.jcc.DB2Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8090